# Site settings
title: The BioFoundry
email: vikramaditya.yadav@ubc.ca
description: The Biofoundry
generic_image: /img/members/avatar2.png
baseurl: "" # the subpath of your site, e.g. /blog/ (If you use organization leave empty)
url: "http://biofoundry.ca" # the base hostname & protocol for your site

#Google Ad Words Data from scripts code (using Google responsive options) and ad client
data-ad-slot: 
data-ad-client: 
google_ad_client: 

google_analytics:
addthis_id: 
disqus_account:

# Social networks usernames (many more available: flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.) see all icon at fontawesome.io
social:
  - title: twitter
    url: http://twitter.com/biofoundry
  - title: facebook-f
    url: https://www.facebook.com/biofoundry
  - title: google-plus
    url: http://plus.google.com/u/0/b/118283831844760263482/118283831844760263482
  - title: github
    url: https://github.com/thebiofoundry

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
# Build settings

# Includes
include: ['_pages']

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  members:
    output: true
    permalink: /members/:path/
  partners: 
    output: true
    permalink: /partners/:path/
  projects:
    output: true
    permalink: /projects/:path/
  teachings:
    output: true
    permalink: /teachings/:path/
  outreach:
    output: true
    permalink: /outreach/:path/
